import Head from 'next/head';
import Link from 'next/link';
import Layout from '../../components/layout';
import layoutStyles from '../../components/layout.module.css';


const Works = () => {
  return (
    <>
      <Head>
        <title>ZonoWorks/Works</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div>
          <h1 className={layoutStyles.h1Text}>Works</h1>
          <div className="flex flex-wrap flex-col items-center mb-20 mt-10 md:mt-20 text-center space-x-5">
            <div>
              <Link href="/posts/PortforioSite">
                <img src="/images/zonoworksImg.jpg" alt="works01の画像" className="max-w-screen-sm max-h-60 mb-5 shadow-lg transition-all duration-300 cursor-pointer hover:translate-x-1 hover:translate-y-1 hover:shadow-none  hover:duration-300" />
              </Link>
            </div>
            <Link href="/posts/PortforioSite">
              <a className="font-bold">ポートフォリオサイト</a>
            </Link>
            <p>私のスキルや経歴をまとめたポートフォリオサイトです。</p>
          </div>
        </div>
      </Layout>
    </>
  )
}

export default Works;