import Head from 'next/head';
import Layout from '../components/layout';
import ContactForm from '../components/templatates/contactForm';

const Contact = () => {
  return (
    <>
      <Head>
        <title>ZonoWorks/Contact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <ContactForm />
      </Layout>
    </>
  )
}

export default Contact