import Head from 'next/head'
import styles from '../styles/Home.module.css'
import 'tailwindcss/tailwind.css';
import About from "./About"
import LoginForm from '../components/templatates/loginForm';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>ZonoWorks</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* <script src="https://kit.fontawesome.com/87974c7c38.js" crossorigin="anonymous"></script> */}
      </Head>

      <About />
      <LoginForm />
    </div>
  )
}
